#!/bin/bash

DATE="$(date +'%d-%m-%y_%H:%M:%S')"
DIR="$HOME/pictures/screenshots"
PIC="$DIR/$DATE.jpg"

[ ! -d "$DIR" ] && mkdir -pv "$DIR"

abort() {
    notify-send -a "Warn" -i dialog-error "Screenshot" "aborted"
    exit 1
}

notification() {
    NOTIFY=$(notify-send -A open=Open -A delete=Delete -a Screenshot -i "$PIC" "Screenshot" "$PIC")
    if [[ $NOTIFY == "open" ]]; then
        viewnior "$PIC"
    elif [[ $NOTIFY == "delete" ]]; then
        rm -rf "$PIC"
    else
        exit 0
    fi
}

case "$1" in
    full)
        flameshot full -p "$PIC" || abort
        #flameshot full -p ~/pictures/screenshots
        xclip -selection primary <"$PIC"
        notification
        ;;
    crop)
        flameshot gui -p "$PIC" || abort
        #flameshot gui -p ~/pictures/screenshots
        xclip -selection primary <"$PIC"
        notification
        ;;
esac
