#!/bin/bash

while true; do
    bg_color="#000000" # Initial background color (white)
    #bg_color="#FFFFFF" # Initial background color (white)
    text_color="#FFFFFF" # Initial text color (black)
    #text_color="#000000" # Initial text color (black)
    font="%{T1}" # Initial font setting

    active_node=$(xdotool getactivewindow)

    if [[ "$1" -eq "$active_node" ]]; then
        bg_color="#000000" # Change the background color when the window is active (white)
        #bg_color="#FFFFFF" # Change the background color when the window is active (white)
        text_color="#FFFFFF" # Change the text color when the window is active (black)
        #text_color="#000000" # Change the text color when the window is active (black)
        font="%{T2}" # Change the font setting when the window is active
    fi

    title=$(xtitle "$1")

    echo -e "%{B$bg_color}%{F$text_color}$font%{c}%{A1:bspc node $1 -f:}%{A2:bspc node $1 -c:}%{A5:bspc node $1 -d last:}%{A4:bspc node $1 -s biggest && ~/.scripts/title-bar:} $title%{A}%{A}%{A}%{A}%{F#FFFFFF}%{r}%{A:bspc node $1 -c:}x   %{A}"
    #echo -e "%{B$bg_color}%{F$text_color}$font%{c}%{A1:bspc node $1 -f:}%{A2:bspc node $1 -c:}%{A5:bspc node $1 -d last:}%{A4:bspc node $1 -s biggest && ~/.scripts/title-bar:}$title%{A}%{A}%{A}%{A}%{F#000000}%{r}%{A:bspc node $1 -c:}x   %{A}"

    sleep 0.5
done
