name: Create Release

on:
  push:
    tags:
      - 'v*' # This triggers the workflow on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download dotfiles zip
        run: |
          mkdir -p $HOME/temp-dotfiles
          cd $HOME/temp-dotfiles
          echo "Downloading dotfiles-main.zip..."
          curl -LOk https://github.com/srdusr/dotfiles/archive/main.zip
          ls -lh main.zip  # Log file size
          unzip main.zip -d dotfiles-main
          mv dotfiles-main/dotfiles-main dotfiles
          ls -lh dotfiles  # Log extracted files

      - name: Create zip file
        run: |
          cd $HOME/temp-dotfiles
          zip -r dotfiles.zip dotfiles

      - name: Move zip file to home directory
        run: |
          mv $HOME/temp-dotfiles/dotfiles.zip $HOME/dotfiles.zip
          ls -lh $HOME/dotfiles.zip # Verify existence after move (optional)

      - name: Clean up
        run: rm -rf $HOME/temp-dotfiles

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Automatically generated release
          draft: false
          prerelease: false

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $HOME/dotfiles.zip
          asset_name: dotfiles.zip
          asset_content_type: application/zip
